### ISSUE TITLE
Would it be possible to make it work for text generation?

### ISSUE THREAD

**Issue by mathigatti** [jobergum/browser-ml-inference#2]
Hey, awesome project, thanks for sharing! Have you tried or do you know of similar demos showing how to run gpt like models in the browser?

**Comment by jobergum** [comment]
Thank you!

I have yet to try generative models, but it's certainly possible. I would look at [T5 Flan](https://huggingface.co/google/flan-t5-small). T5 and T5 flan has the same inference and architecture, just different training.

**Comment by mathigatti** [comment]
Thanks! I will check it
